[build-system]
requires = ["setuptools","wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "revisao_github"
version = "1.0.0"
dependencies = ["requests"]

[tool.setuptools]
packages = ["src"]


[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "black"
]