name: Estudo de Constant Delivery

on:
  workflow_dispatch: 

jobs:
  upload_artifact:
    name: Upando Relatório do pytest
    runs-on: ubuntu-latest

    steps:
      - name: Upando repositorio para o runner
        uses: actions/checkout@v6.0.2

      - name: Criando ambiente python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.13'

      - name: Baixando o pytest
        run: pip install pytest

      - name: Rodando o pytest e gerando relatório
        run: pytest --junitxml=pytest-report.xml

      - name: Upando o artefato para a o github-actions
        uses: actions/upload-artifact@v6.0.0
        with:
          name: pytest-report.xml
          path: dist/
        
        
