# Workflow para estudar CI
name: Estudo de CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  testes:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.13, 3.14]
        
    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v6.0.2
    
      - name: Configurando Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: ${{matrix.python-version}}

      - name: Instalando dependencias
        run: pip install selenium bs4 aiohttp pytest

      - name: Fianlizando  Pipeline
        run: echo "Pipeline CI Finalizada!"

        
      
    
